### ISSUE TITLE
Not working on Big Sur 11.1

### ISSUE THREAD

**Issue by serebro** [zvonicek/radium-fix-launcher#2]
It gives a popup window with the message "Trial period is over. To continue using Radium, buy it on the Mac App Store." and two buttons: "Mac App Store" and "Quit Radium". Please help.

**Comment by iMongui** [comment]
Very simple, you need to own the app in order to use it, if you just use the trial, well... that's the result

**Comment by zvonicek** [comment]
Thanks for the indeed correct response @iMongui!
